version: '3.9'
services:
  image-server:
    build:
      context: .
      dockerfile: dockerfile
    container_name: image-server
    networks:
      - my_app_network
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    command: gunicorn --bind 0.0.0.0:5000 "app:create_app()"

networks:
  my_app_network:
    external: true  # Use the shared external network
