version: '3.9'
services:
  image-server:
    build:
      context: .
      dockerfile: dockerfile
    container_name: image-server
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always